import {DetailsModel} from "../models/DetailsModel";

export const DetailsElements: DetailsModel [] = [
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Name",
            placeholder: "Name",
            order: 0,
            editable: false,
            sortable: false,
            id: "",
            defaultElement: true,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Title",
            placeholder: "Title",
            order: 1,
            editable: false,
            sortable: false,
            id: "",
            defaultElement: true,

        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Company",
            placeholder: "Company",
            order: 2,
            editable: false,
            sortable: false,
            id: "",
            defaultElement: true,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Phone",
            placeholder: "Phone",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: true,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Mobile",
            placeholder: "Mobile",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: true,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Website",
            placeholder: "Website",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: true,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Email",
            placeholder: "Email",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: true,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Address",
            placeholder: "Address",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: true,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Pronouns",
            placeholder: "Pronouns",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: false,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Extension",
            placeholder: "Extension",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: false,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Fax",
            placeholder: "Fax",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: false,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Skype",
            placeholder: "Skype",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: false,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Hangout",
            placeholder: "Hangout",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: false,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Zoom",
            placeholder: "Zoom",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: false,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Meet",
            placeholder: "Meet",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: false,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Whatsapp",
            placeholder: "Whatsapp",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: false,
        },
        {
            value: "",
            clickable: false,
            deletable: false,
            type: "text",
            name: "Telegram",
            placeholder: "Telegram",
            order: 3,
            editable: true,
            sortable: true,
            id: "",
            defaultElement: false,
        },
    ]
;
