import { SocialsModel } from "../models/SocialsModel";

export const SocialsElements: SocialsModel[] = [
  {
    url: "",
    defaultIcon: true,
    network: "facebook",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: true,
    network: "instagram",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: true,
    network: "twitter",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: true,
    network: "linkedin",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "meetup",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: true,
    network: "pinterest",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "dropbox",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: true,
    network: "youtube",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "bandsintown",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "behance",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "codepen",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "discord",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "dribbble",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "email",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "fivehundredpix",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "flickr",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "foursquare",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "github",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "google_play",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "google",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "itch.io",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "itunes",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "mailto",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "medium",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "rdio",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "reddit",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "rss",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "sharethis",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "smugmug",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "snapchat",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "soundcloud",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "spotify",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "squarespace",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "stackoverflow",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "telegram",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "tiktok",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "tumblr",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "twitch",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "vevo",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "vimeo",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "vine",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "vk",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "vsco",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "wechat",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "whatsapp",
    id: "",
    chosen: false,
    selected: false,
  },
  {
    url: "",
    defaultIcon: false,
    network: "yelp",
    id: "",
    chosen: false,
    selected: false,
  },
];
